version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: aws-sdk
    versions:
    - "> 2.761.0"
  - dependency-name: framer-motion
    versions:
    - 3.10.0
    - 3.10.2
    - 3.10.3
    - 3.10.5
    - 3.2.1
    - 3.3.0
    - 3.5.2
    - 3.6.2
    - 3.6.7
    - 3.7.0
    - 3.9.0
    - 3.9.1
    - 4.0.0
    - 4.0.3
    - 4.1.10
    - 4.1.2
    - 4.1.3
    - 4.1.5
    - 4.1.6
    - 4.1.8
    - 4.1.9
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: react-slideshow-image
    versions:
    - 3.4.3
    - 3.4.5
  - dependency-name: aws-amplify
    versions:
    - 3.3.15
    - 3.3.16
    - 3.3.17
    - 3.3.18
    - 3.3.19
    - 3.3.20
    - 3.3.21
    - 3.3.22
    - 3.3.23
    - 3.3.24
    - 3.3.25
    - 3.3.26
  - dependency-name: framer
    versions:
    - 1.2.16
    - 1.2.18
    - 1.2.20
    - 1.2.21
    - 1.2.22
    - 1.2.23
    - 1.2.24
    - 1.2.25
    - 1.2.26
    - 1.2.27
    - 1.2.28
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.34
