language: node_js
node_js:
  - 15
branches:
   only:
      - develop
before_install:
  - git clone https://areksds:$GITHUB_KEY@github.com/covalentapp/aws-exports.js.git
  - mv aws-exports.js/aws-exports.js src/
  - rm -r aws-exports.js
script: npm build
notifications:
  slack: covalentdev:$SLACK