/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://eaauuzyytvafhn4kvngk3bj72q.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nzk5qomc2fh4vhmktaoevbsi2m",
    "aws_cognito_identity_pool_id": "us-east-1:2f47afb9-2635-4a85-92c0-e60d26829ea5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_IGF5p7qUt",
    "aws_user_pools_web_client_id": "46rmgq4c6aenorndq1q7n4n5l7",
    "oauth": {},
    "aws_user_files_s3_bucket": "covalentbackendb12268d8d3b74fbcb845a5646024a33e214538-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
